const UPDATE_FIELD = "UPDATE_FIELD";
const SUBMIT_RATE = "SUBMIT_RATE";
const SUBMIT_GRATITUDE = "SUBMIT_GRATITUDE";
const SUBMIT_GOAL = "SUBMIT_GOAL";
const GO_BACK = "GO_BACK";

export { UPDATE_FIELD, SUBMIT_RATE, SUBMIT_GRATITUDE, SUBMIT_GOAL, GO_BACK };
