const TOGGLE_TICK = 'TOGGLE_TICK';
const UPDATE_TIME = 'UPDATE_TIME';
const UPDATE_PROJECT = 'UPDATE_PROJECT';
const UPDATE_MODE = 'UPDATE_MODE';
const UPDATE_COUNT = 'UPDATE_COUNT';
const ADD_SESSION = 'ADD_SESSION';

export {
  TOGGLE_TICK,
  UPDATE_TIME,
  UPDATE_PROJECT,
  UPDATE_MODE,
  UPDATE_COUNT,
  ADD_SESSION,
};
