const TOGGLE_TICK = 'TOGGLE_TICK';
const TOGGLE_EDIT = 'TOGGLE_EDIT';
const UPDATE_TIME = 'UPDATE_TIME';
const UPDATE_PROJECT = 'UPDATE_PROJECT';
const UPDATE_MODE = 'UPDATE_MODE';
const UPDATE_COUNT = 'UPDATE_COUNT';
const ADD_SESSION = 'ADD_SESSION';
const INIT_EDIT_MODE = 'INIT_EDIT_MODE';
const UPDATE_TIME_AND_EDIT = 'UPDATE_TIME_AND_EDIT';
const UPDATE_EDIT_TIME = 'UPDATE_EDIT_TIME';
const RELOAD_STATE = 'RELOAD_STATE';

export {
  TOGGLE_TICK,
  TOGGLE_EDIT,
  UPDATE_TIME,
  UPDATE_PROJECT,
  UPDATE_MODE,
  UPDATE_COUNT,
  ADD_SESSION,
  INIT_EDIT_MODE,
  UPDATE_TIME_AND_EDIT,
  UPDATE_EDIT_TIME,
  RELOAD_STATE,
};
